/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import gb.*;

public class AppTest {
    //@Test public void testAppHasAGreeting() {
    //    FullGB classUnderTest = new FullGB();
    //}
}
